wandb_version: 1

lr:
  desc: null
  value: 1.0202549097253029
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.19.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736453531
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.19.2
      8:
      - 5
      13: darwin-arm64
batch-size:
  desc: null
  value: 64
